services:
  backend:
    environment:
      APP_EDITION: homelab
      SESSION_COOKIE_NAME: session_token_homelab
      CSRF_COOKIE_NAME: csrf_token_homelab

  frontend:
    build:
      args:
        REACT_APP_CSRF_COOKIE_NAME: csrf_token_homelab
        VITE_CSRF_COOKIE_NAME: csrf_token_homelab
